version: '2.4'

services:
  service-config:
    image: application/config-server:naive
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SERVER_PORT: 8080
      EUREKA_CLIENT_ENABLED: "false"

  examinator:
    image: application/examinator:naive
    depends_on:
      service-config:
        condition: service_healthy
      provider-math:
        condition: service_healthy
      provider-theology:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SERVER_PORT: 8080
      EUREKA_CLIENT_ENABLED: "false"
      CONFIG_URL: http://service-config:8080/
    ports:
      - 8093:8080

  provider-math:
    image: application/provider-math:naive
    depends_on:
      service-config:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SERVER_PORT: 8080
      EUREKA_CLIENT_ENABLED: "false"
      CONFIG_URL: http://service-config:8080/

  provider-theology:
    image: application/provider-theology:naive
    depends_on:
      service-config:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      SERVER_PORT: 8080
      EUREKA_CLIENT_ENABLED: "false"
      CONFIG_URL: http://service-config:8080/
    ports:
      - 8083:8080