apiVersion: apps/v1
kind: Deployment
metadata:
  name: examinator-deployment
  namespace: challenges-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: examinator
  template:
    metadata:
      labels:
        name: examinator
    spec:
      containers:
        - name: challenges-provider-container
          image: application/examinator:layered
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: CONFIG_URL
              value: "http://service-config:8080/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-math-deployment
  namespace: challenges-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend-math
  template:
    metadata:
      labels:
        name: backend-math
    spec:
      containers:
        - name: challenges-provider-math-container
          image: application/provider-math:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SERVER_PORT
              value: "8080"
            - name: CONFIG_URL
              value: "http://service-config:8080/"
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-theology-deployment
  namespace: challenges-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend-theology
  template:
    metadata:
      labels:
        name: backend-theology
    spec:
      containers:
        - name: challenges-provider-theology-container
          image: application/provider-theology:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SERVER_PORT
              value: "8080"
            - name: CONFIG_URL
              value: "http://service-config:8080/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-config-deployment
  namespace: challenges-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: config-server-pod
  template:
    metadata:
      labels:
        name: config-server-pod
    spec:
      containers:
        - name: service-config-container
          image: application/config-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SERVER_PORT
              value: "8080"