server:
  port: 8083

spring:
  application:
    name: MATH
  config:
    import: optional:configserver:${CONFIG_URL:http://localhost:8888/}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"